services:
  database:
    image: postgis/postgis:17-3.4
    container_name: trade-business-gis-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trade_business_gis
    ports:
      - "15432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - /Users/lkvkn/postgres/backups/:/backups
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  users-service:
    container_name: users-service
    build:
      dockerfile: users-service/Dockerfile
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
    ports:
      - "18081:18081"
    command: [
      "java",
      "-jar",
      "/app/app.jar"
    ]

  flyway-migrate:
    image: flyway/flyway
    environment:
      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      FLYWAY_SCHEMAS: public
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 30
    command: migrate
    networks:
      - app-network
    volumes:
      - ./migration/:/flyway/sql

  flyway-repair:
    image: flyway/flyway
    environment:
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: >
      -url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} 
      -schemas=public
      -user=${DB_USERNAME} 
      -password=${DB_PASSWORD}
      -connectRetries=5
      repair
    networks:
      - app-network
    volumes:
      - ./migration/:/flyway/sql

volumes:
  postgis_data:
    name: geo_surf_postgis_data

networks:
  app-network:
    name: trade_business_gis-network
    driver: bridge
